sudo: required
language: java
install: false #true

services:
  - docker

jobs:
  include:
    - stage: build (compile, unit test, package)
      jdk: openjdk10
      script:
        - ./gradlew build #--scan -s
        #  - ls -l build/libs
        - docker build -t eoepca/catalogue-service .
        #  - docker images
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag eoepca/catalogue-service $DOCKER_USERNAME/catalogue-service:travis_$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_USERNAME/catalogue-service:travis_$TRAVIS_BUILD_NUMBER   # defaults to docker hub
      
    - stage: smoke and acceptance test
      install: skip  # without this there's a git clone and gradlew assemble executed! 
      script:
        - docker run -d --rm -p 8080:7000 --name cat-svc $DOCKER_USERNAME/catalogue-service:travis_$TRAVIS_BUILD_NUMBER
        - sleep 15  # wait for startup
      #  - docker ps -a
        - curl -s http://localhost:8080/search | jq '.'  # trivial smoke test
      #  - docker logs cat-svc
      
    - stage: release
      if: branch = master
      install: skip
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull $DOCKER_USERNAME/catalogue-service:travis_$TRAVIS_BUILD_NUMBER  # have to pull locally in order to tag as a release 
        - docker tag $DOCKER_USERNAME/catalogue-service:travis_$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/catalogue-service:release_$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_USERNAME/catalogue-service:release_$TRAVIS_BUILD_NUMBER

notifications:
  email:
    recipients:
      - paul.cox@telespazio.com
      - richard.conway@telespazio.com
    on_success: never #never # default: change
    on_failure: never # default: always
