sudo: required

language: java
install: false #true

jdk:
  - openjdk10

services:
  - docker

jobs:
  include:
    - stage: build (compile, unit test, package)
      script:
        - ./gradlew build #--scan -s
      #  - ls -l build/libs
        - docker build -t eoepca/catalogue-service .
      #  - docker images
      
    - stage: smoke test
      script:
        - docker run -d --rm -p 8080:7000 --name cat-svc eoepca/catalogue-service
        - sleep 15
      #  - docker ps -a
        - curl -s http://localhost:8080/search | jq '.'
      #  - docker logs cat-svc
      
    - stage: docker push      
      - script
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag eoepca/catalogue-service $DOCKER_USERNAME/catalogue-service
        - docker push $DOCKER_USERNAME/catalogue-service   # defaults to docker hub

notifications:
  email:
    recipients:
      - paul.cox@telespazio.com
      - richard.conway@telespazio.com
    on_success: never #never # default: change
    on_failure: never # default: always
