
# equivalent to
# kubectl expose deployment catalogue-service-deployment --name=cat-svce --port=8080 --target-port=7000 --type=NodePort
apiVersion: v1
kind: Service
metadata:
  name: cat-svce  # DNS name?
spec:
  type: NodePort  # TODO
  # selector:
  #   app: catalogue-service
  #   tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 7000
    name: http



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-service-deployment
spec:
  selector:
    matchLabels:
      app: catalogue-service
  replicas: 1 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: catalogue-service
    spec:
      containers:
      # - name: nginx
      #   image: nginx:1.7.9
      #   ports:
      #   - containerPort: 80
      - name: cat-svce
        image: eoepcaci/catalogue-service:latest # may not always want latest
        ports:
        - containerPort: 7000
