apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sample-eo-data
  #namespace: eo-user-compute across namespaces?
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce  # read/write by a single node
  persistentVolumeReclaimPolicy: Retain
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#writing-portable-configuration
   storageClassName: null # make it default for portability
#  mountOptions:
#  - hard
#  - nfsvers=4.1
#  nfs:
#    path: /tmp
#    server: 172.17.0.2

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sample-eo-data
  namespace: eo-user-compute
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi   # Only 3GB required
#  storageClassName: slow
  selector:
    matchLabels:
      release: pv-sample-eo-data   # matches the PV
#    matchExpressions:
#    - {key: environment, operator: In, values: [dev]}
