apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sample-eo-data-1
  labels:
    vol-type: eo-end-user-data
    vol-id: vol_1999
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce  # read/write by a single node
  persistentVolumeReclaimPolicy: Retain
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#writing-portable-configuration
   #storageClassName: ???
  hostPath:  # volume type - dev/test only on minikube
    path: /mnt

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sample-eo-data-2
  labels:
    vol-type: eo-end-user-data
    vol-id: vol_0001
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce  # read/write by a single node
  persistentVolumeReclaimPolicy: Retain
    # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#writing-portable-configuration
  #storageClassName: ???
  hostPath:  # volume type - dev/test only on minikube
    path: /mount

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sample-eo-data
  namespace: eo-user-compute
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi   # Only 1GB required
#  storageClassName: slow
  selector:
    matchLabels:
      vol-type: eo-end-user-data   # matches the PV labels
      vol-id: vol_1999
#    matchExpressions:
#    - {key: environment, operator: In, values: [dev]}
