apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sample-eo-data
  #namespace: eo-user-compute across namespaces?
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce  # read/write by a single node
  persistentVolumeReclaimPolicy: Retain
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#writing-portable-configuration
   #storageClassName: ???
  hostPath:  # volume type - dev/test only on minikube
    path: /eo-data

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sample-eo-data
  namespace: eo-user-compute
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi   # Only 1GB required
#  storageClassName: slow
  selector:
    matchLabels:
      release: pv-sample-eo-data   # matches the PV
#    matchExpressions:
#    - {key: environment, operator: In, values: [dev]}
