apiVersion: v1
kind: List
items:      # count batch pods
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: batch-jobs
    namespace: eo-user-compute
  spec:
    hard:
      count/jobs.batch: 1

#- apiVersion: v1
#  kind: ResourceQuota
#  metadata:
#    name: pods-high
#    namespace: eo-user-compute
#  spec:
#    hard:
#      cpu: "1000"
#      memory: 200Gi
#      pods: "10"
#    scopeSelector:
#      matchExpressions:
#      - operator : In
#        scopeName: PriorityClass
#        values: ["high"]
#- apiVersion: v1
#  kind: ResourceQuota
#  metadata:
#    name: pods-medium
#    namespace: eo-user-compute
#  spec:
#    # count/jobs.batch   TODO
#    hard:
#      cpu: "10"
#      memory: 20Gi
#      pods: "10"
#    scopeSelector:
#      matchExpressions:
#      - operator : In
#        scopeName: PriorityClass
#        values: ["medium"]
#- apiVersion: v1
#  kind: ResourceQuota
#  metadata:
#    name: pods-low
#    namespace: eo-user-compute
#  spec:
#    hard:
#      cpu: "5"
#      memory: 10Gi
#      pods: "10"
#    scopeSelector:
#      matchExpressions:
#      - operator : In
#        scopeName: PriorityClass
#        values: ["low"]

